# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
