# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0002_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
    ]
